[package]
name = "duckdb-http-api"
version = "0.1.0"
edition = "2024"

[dependencies]
duckdb = { version = "1.3.2", features = ["bundled"] }
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
axum-server = "0.7.2"
